version: '3.7'
services:
  # NGINX
  nginx:
    container_name: nginx
    image: nginx:1.18.0
    ports:
      - '80:80'
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/log:/var/log/nginx
      - ./html:/var/www/html:ro
    depends_on:
      - node
    restart: always
    
  # Node.js
  node:
    container_name: node
    build:
      context: dockerfiles
      dockerfile: Dockerfile_nodejs
    volumes:
      - ./node/nextapp:/src/app
    working_dir: /src/app
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
    command: /bin/sh -c 'yarn ${NEXT_APP_ENV}'
    restart: always
    init: true
    tty: true

  # MySQL
  mysql:
    container_name: mysql
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password --port ${MYSQL_PORT}
    volumes:
      - ./mysql/data:/var/lib/mysql:cached
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d:ro
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_HOST=${MYSQL_ROOT_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    restart: always
    security_opt:
      - seccomp:unconfined
